### ISSUE TITLE
Execution reverted: BAL#520 when calling joinPool on a Managed Pool to add ETH

### ISSUE THREAD

**Issue by BenAzlay** [balancer/balancer-v2-monorepo#2548]
I am trying to join a Managed Pool for WETH and an ERC20, and I want to add ETH directly. This is my code:

```JS
const ethAddress = ethers.ZeroAddress; // Using the zero address for ETH
await vaultContract.methods.joinPool(
            poolId,
            walletAddress,
            walletAddress,
            [
                [
                    poolAddress,
                    otherTokenAddress,
                    ethAddress,
                ],
                [
                    "0",
                    otherTokenAmount,
                    "0",
                ],
                userData,
                false,
            ]
        ).send({
                from: walletAddress,
                value: ethAmount,
            });
```
When trying to execute this I get the **BAL#520 TOKENS_MISMATCH** error.

My assets array is in the same order as what is returned by the getPoolTokens method.

I put "0' for the WETH amount in maxAmountsIn because I am sending ETH and not WETH. But it has the same error when I put the ETH amount in maxAmountsIn.

I've tried to reorder maxAmountsIn and assets, but it didn't change the outcome.

How can I avoid the TOKENS_MISMATCH error?

**Comment by EndymionJkb** [comment]
This definitely works; ETH wrapping/unwrapping happens at the Vault level, so you can do it with any operation on any pool. The tricky thing with composable pools (Composable Stable and Managed) is getting the arrays right everywhere.

Tokens are sorted, so if the pool really is [poolAddress, otherTokenAddress, WETH], you would pass in:

assets: [poolAddress, otherTokenAddress, 0] // length 3 - need all tokens
limits: [0, otherTokenLimit, EthLimit] // length 3 - need all tokens, and the Eth limit must be > 0
amounts: [otherTokenAmount, EthAmount] // encoded in userData - note it is length *2*, does not include the pool token

Before doing this, you'd have to create the pool with WETH and otherTokenAddress, and initialize it with WETH and the other token. (I suppose you could initialize it with ETH, too; that's just a join.)

Make sure the WETH you're using is the Vault's WETH (assuming you are doing this in a test network). I suspect this might be your problem, since you seem to understand the array inputs well enough. You have to pass the WETH address in when you deploy the Vault, and that's the token it recognizes for wrapping/unwrapping.

If you just deployed something called WETH and are using that, the Vault will not recognize it, and it will stay 0 instead of getting translated to WETH. So the Vault will compare 0 to its internal WETH, and revert with a TOKENS_MISMATCH

**Comment by BenAzlay** [comment]
> You don't say what kind of join, but I assume it's an ExactTokensInForBptOut, so you'd need to encode userData with that join type and (amountsIn, minBptAmountOut).

This is how I generated userData, is it correct?:

```JS
const joinKind = "0";
const initBalances = [
      otherTokenAmountWei,
      ethAmountWei,
];
const abi = ['uint256', 'uint256[]'];
const data = [joinKind, initBalances];
const userData = defaultAbiCoder.encode(abi,data);
```

> Make sure the WETH you're using is the Vault's WETH (assuming you are doing this in a test network). I suspect this might be your problem, since you seem to understand the array inputs well enough.

Sure but here I am staking ETH, so there is nowhere I should put the WETH address of the pool, right?

This is the WETH token I am using on Sepolia: https://sepolia.etherscan.io/token/0xfFf9976782d46CC05630D1f6eBAb18b2324d6B14

**Comment by EndymionJkb** [comment]
So it looks like you're doing this "live" on a public testnet, not in a hardhat or forge test. The Sepolia Vault is [here](https://sepolia.etherscan.io/address/0xBA12222222228d8Ba445958a75a0704d566BF2C8#readContract), and calling WETH() gives you the [Sepolia WETH](https://sepolia.etherscan.io/address/0x7b79995e5f793A07Bc00c21412e50Ecae098E7f9) the Vault is using.

So first of all you need to use that WETH (i.e., deploy a pool with that WETH). So what is happening is what I described above. Your 0 ETH sentinel will get converted to 0x7b7999..., which then won't match the pool's "WETH" 0xfFf99..., and it reverts with a TOKEN_MISMATCH.

An init join should also work with ETH, and that does look right. You just have to deploy a pool with the correct WETH for Sepolia.
